FROM homebridge/homebridge:latest

USER root
RUN npm install -g homebridge-acinfinity@1.3.6 homebridge-meross@10.8.1

# Run as root so dbus-daemon can bind /run/dbus/system_bus_socket inside the container
USER root
